---
title: "Factor analysis"
author: "Kristine Torp"
date: "11/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

###PRINCIPAL COMPONENT ANLYSIS AND FACTOR ANALYSIS

pacman::p_load("tidyverse","tseries", "psych","GPArotation", "mvtnorm", "polycor","corpcor","GPArotation","pastecs", "corrgram", "e1071")

#Loaded data
df_anxiety <- read_csv("anxiety.csv")


#try deleting column names and the ID column - because??

#deleting ID column 
df_anxiety <- df_anxiety[,-1]

#flip the scores for positive questions in stai y1
library(car)

# ##this is just ready for when I get the stai y1 data - but it might not be necessary 
# d$stai_1 <- car::recode(d$stai_1, "4=1; 3=2; 2=3; 1=4")
# d$stai_2 <- car::recode(d$stai_2, "4=1; 3=2; 2=3; 1=4")
# d$stai_5 <- car::recode(d$stai_5, "4=1; 3=2; 2=3; 1=4")
# d$stai_8 <- car::recode(d$stai_8, "4=1; 3=2; 2=3; 1=4")
# d$stai_10 <- car::recode(d$stai_10, "4=1; 3=2; 2=3; 1=4")
# d$stai_11 <- car::recode(d$stai_11, "4=1; 3=2; 2=3; 1=4")
# d$stai_15 <- car::recode(d$stai_15, "4=1; 3=2; 2=3; 1=4")
# d$stai_16 <- car::recode(d$stai_16, "4=1; 3=2; 2=3; 1=4")
# d$stai_19 <- car::recode(d$stai_19, "4=1; 3=2; 2=3; 1=4")
# d$stai_20 <- car::recode(d$stai_20, "4=1; 3=2; 2=3; 1=4")

#flip the scores for positive questions in stai y2
df_anxiety$stai_21 <- car::recode(df_anxiety$stai_21, "4=1; 3=2; 2=3; 1=4")
df_anxiety$stai_23 <- car::recode(df_anxiety$stai_23, "4=1; 3=2; 2=3; 1=4")
df_anxiety$stai_26 <- car::recode(df_anxiety$stai_26, "4=1; 3=2; 2=3; 1=4")
df_anxiety$stai_27 <- car::recode(df_anxiety$stai_27, "4=1; 3=2; 2=3; 1=4")
df_anxiety$stai_30 <- car::recode(df_anxiety$stai_30, "4=1; 3=2; 2=3; 1=4")
df_anxiety$stai_33 <- car::recode(df_anxiety$stai_33, "4=1; 3=2; 2=3; 1=4")
df_anxiety$stai_34 <- car::recode(df_anxiety$stai_34, "4=1; 3=2; 2=3; 1=4")
df_anxiety$stai_36 <- car::recode(df_anxiety$stai_36, "4=1; 3=2; 2=3; 1=4")
df_anxiety$stai_39 <- car::recode(df_anxiety$stai_39, "4=1; 3=2; 2=3; 1=4")


#find correlation matrix of data
cor_matrix <- cor(df_anxiety, use = "complete.obs")

#view correlation matrix
cor_matrix

#Bartlett test - I want it to be significant - means that the correlations are significantly different from zero 
cortest.bartlett(df_anxiety)

#The principal component analysis 
pca1 <- princomp(na.omit(df_anxiety), scores = TRUE, cor = TRUE)

summary(pca1) #looking at this summary I might have five components 
#- Look for eigen values above 1 - means they explain at least as much variance as the actual variable

loadings(pca1) #we want to see low loadings on the components 

plot(pca1)

#making a screeplot 
screeplot(pca1, type ="line", main = "screeplot")

#not a usefull plot - how the original variables line up in the component plot 
biplot(pca1)


#Running a parallel test (Horn's) -## why am I doing this??
parallel <- fa.parallel(df_anxiety, fm ="minres", fa ="fa", sim = FALSE)
# I think this plot shows that I need 3 factors


pca1$scores
```


```{r}
#Check from how many participants we have complete data from - because only those will be used in the factor analysis. 
sum(complete.cases(df_anxiety)) #224 partcipants - that is fine 

#checking if my data is factor analysis friendly - both tests tell me that they are. 
cortest.bartlett(df_anxiety)
KMO(df_anxiety)


#Screeplot 
scree(df_anxiety)

#a better evaluation of the screeplot
fa.parallel(df_anxiety)

#Factor analysis 
fa.out <- fa(df_anxiety,nfactors = 3, fm="pa", max.iter = 100,rotate = "oblimin")

print(fa.out, digits = 3, cutoff = 0.3, sort = FALSE)

#The plot Micah wants
fa.diagram(fa.out)

fa.out$communality

#making a dataframe with the loadings 
f1<-fa.out$loadings[,1]
f2<-fa.out$loadings[,2]
f3<-fa.out$loadings[,3]

loadings<-data.frame(f1,f2,f3)

text <- rownames(loadings)

loadings$Qname <- cbind(text)


#add a new  column to loadings where each questionaire gets their own number 
library("stringr")
loadings<- loadings %>% 
  mutate(quest = if_else(str_starts(Qname,"stai_"), 1, 2))

loadings$quest <- as.factor(loadings$quest)


#making different plots to investigate the factors 

p1 <- ggplot(loadings,aes(x=f1,y=f2, colour = quest ))+
 geom_point(size=2)+
  coord_cartesian(xlim =c(-1,1), ylim = c(-1,1))

 p1

p2 <- ggplot(loadings, aes(x=f1,y=f3, colour = quest ))+
 geom_point(size=2)+
  coord_cartesian(xlim =c(-1,1), ylim = c(-1,1))

p2

p3 <- ggplot(loadings, aes(x=f2,y=f3, colour = quest ))+
 geom_point(size=2)+
  coord_cartesian(xlim =c(-1,1), ylim = c(-1,1))

p3



#install.packages("scatterplot3d") # Install
library("scatterplot3d") # load

scatterplot3d(loadings[,1:3],pch = 16, color= "steelblue", angle = 40,
              main="3D Scatter Plot",
              xlim = c(-1,1),
              ylim = c(-1,1),
              zlim = c(-1,1),
              xlab = "f1",
              ylab = "f2",
              zlab = "f3")
fa.diagram(loadings)



```


```{r}
#Don't think this is useful 

#Well this gives me which participant that has the lowest or highest score....
#figuring out which partcipant that scores lowest on each factor 
which.min(fa.out$scores[,1])

which.min(fa.out$scores[,2])

which.min(fa.out$scores[,3])

#figuring out which participant that scores highest on each factor 

which.max(fa.out$scores[,1])

which.max(fa.out$scores[,2])

which.max(fa.out$scores[,3])
```
```{r}
#trying to save the fa.diagram 

# 1. Open jpeg file
jpeg("rplot.jpg", width = 350, height = 350)
# 2. Create the plot
fa.diagram(fa.out)
# 3. Close the file
dev.off()
```




